### ISSUE TITLE
Fail to install SpeckleBlender for Blender 2.82

### ISSUE THREAD

**Issue by htlcnn** [speckleworks/SpeckleBlender#15]
I installed SpeckleBlender for Blender 2.82.
When I activate the addon, Blender says:
```
Modules Installed (bpy_speckle) from 'D:\\HTL\\Desktop\\bpy_speckle.zip' into 'C:\\Users\\HTL\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons'

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\HTL\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\bpy_speckle\__init__.py", line 53, in <module>
    from speckle import SpeckleApiClient, SpeckleCache
ModuleNotFoundError: No module named 'speckle'
```
I have tried running Blender as administrator but no luck.

**Comment by htlcnn** [comment]
It's my bad. I had to restart Blender before enabling the addon.

**Comment by nortikin** [comment]
```bash
ERROR: qtconsole 4.7.3 requires pygments, which is not installed.
ERROR: notebook 6.0.3 requires jinja2, which is not installed.
ERROR: nbconvert 5.6.1 requires entrypoints>=0.2.2, which is not installed.
ERROR: nbconvert 5.6.1 requires jinja2>=2.4, which is not installed.
ERROR: nbconvert 5.6.1 requires pygments, which is not installed.
ERROR: jupyter-console 6.1.0 requires pygments, which is not installed.
ERROR: ipython 7.14.0 requires pexpect; sys_platform != "win32", which is not installed.
ERROR: ipython 7.14.0 requires pygments, which is not installed.
ERROR: cpython 0.0.5 requires pymongo, which is not installed.
ERROR: bleach 3.1.5 requires packaging, which is not installed.
WARNING: Target directory /home/ololo/.config/blender/2.82/scripts/addons/modules/pydantic already exists. Specify --upgrade to force replacement.
Traceback (most recent call last):
  File "/home/ololo/Downloads/INSTALL/blender-2.82-linux64/2.82/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/ololo/.config/blender/2.82/scripts/addons/bpy_speckle/__init__.py", line 53, in <module>
    from speckle import SpeckleApiClient, SpeckleCache
ModuleNotFoundError: No module named 'speckle'
```

**Comment by tsvilans** [comment]
@nortikin is this with a fresh install of Speckle? Looks like you're on Linux?

I'm a bit perplexed by `qtconsole`, `notebook`, and the others... I don't think they should be dependencies for `speckle`...

**Comment by nortikin** [comment]
> I'm a bit perplexed
linux debian 10
i see this strange:
```sh
ERROR: ipython 7.14.0 requires pexpect; sys_platform != "win32", which is not installed.
```
